import {useEffect,useRef,useState} from 'react';
import type {CrosshairConfig} from '../utils/crosshair';
import CrosshairView from '../utils/CrosshairView';
import type {Difficulty} from '../utils/storage';
export interface MicroFlickResult{score:number;accuracy:number;hits:number;shots:number;avgReactionMs:number;bestReactionMs:number;avgDistance:number;overshoots:number;duration:number;difficulty:Difficulty}
interface Props{onBack:()=>void;onFinish:(r:MicroFlickResult)=>void;crosshair:CrosshairConfig}
const DIFF:Record<Difficulty,{label:string;size:number;gap:number;life:number}>=
{newbie:{label:'응애 나 뉴비에요',size:42,gap:65,life:1500},normal:{label:'이제 사람 구실 좀 해볼게요',size:37,gap:48,life:1100},hard:{label:'나 정도면 실력자지',size:33,gap:34,life:820},hell:{label:'경쟁에서 캐리할게요',size:29,gap:25,life:620}};
const TOTAL=30;let audio:AudioContext|null=null;
function sound(ok:boolean){try{const C=window.AudioContext||(window as any).webkitAudioContext;if(!C)return;audio??=new C();if(audio.state==='suspended')void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=ok?360:90;g.gain.setValueAtTime(ok?.032:.015,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.06);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.06)}catch{}}
export default function MicroFlickGame({onBack,onFinish,crosshair}:Props){
 const[phase,setPhase]=useState<'intro'|'live'>('intro'),[difficulty,setDifficulty]=useState<Difficulty>('normal'),[time,setTime]=useState(TOTAL),[target,setTarget]=useState({x:50,y:50}),[shots,setShots]=useState(0),[hits,setHits]=useState(0),[combo,setCombo]=useState(0),[feedback,setFeedback]=useState<'hit'|'miss'|''>('');
 const start=useRef(0),born=useRef(0),last=useRef({x:50,y:50}),active=useRef(false),react=useRef<number[]>([]),dist=useRef<number[]>([]),over=useRef(0),stage=useRef<HTMLDivElement>(null),raf=useRef(0),feedbackTimer=useRef<number|undefined>(undefined),hitsRef=useRef(0),shotsRef=useRef(0);
 const next=()=>{const d=DIFF[difficulty];const a=Math.random()*Math.PI*2,rad=d.gap*(.8+Math.random()*.45);setTarget({x:Math.max(8,Math.min(92,last.current.x+Math.cos(a)*rad/6)),y:Math.max(10,Math.min(90,last.current.y+Math.sin(a)*rad/6))});born.current=performance.now();active.current=true};
 const finish=()=>{if(!active.current&&phase!=='live')return;active.current=false;cancelAnimationFrame(raf.current);const s=Math.max(1,shotsRef.current),acc=hitsRef.current/s*100,avg=react.current.length?react.current.reduce((a,b)=>a+b,0)/react.current.length:999,bd=dist.current.length?dist.current.reduce((a,b)=>a+b,0)/dist.current.length:99;const score=Math.round(Math.max(0,Math.min(100,acc*.58+Math.max(0,100-avg*.32)*.25+Math.max(0,100-bd*2)*.17-over.current*1.2)));onFinish({score,accuracy:acc,hits:hitsRef.current,shots:shotsRef.current,avgReactionMs:avg,bestReactionMs:react.current.length?Math.min(...react.current):999,avgDistance:bd,overshoots:over.current,duration:Math.min(TOTAL,(performance.now()-start.current)/1000),difficulty})};
 useEffect(()=>{if(phase!=='live')return;start.current=performance.now();react.current=[];dist.current=[];over.current=0;setTime(TOTAL);setShots(0);setHits(0);hitsRef.current=0;shotsRef.current=0;setCombo(0);setFeedback('');next();
   const loop=(now:number)=>{const elapsed=(now-start.current)/1000;const left=Math.max(0,Math.ceil(TOTAL-elapsed));setTime(left);if(left<=0){finish();return}
      raf.current=requestAnimationFrame(loop);
   };raf.current=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf.current);if(feedbackTimer.current)window.clearTimeout(feedbackTimer.current)};
 },[phase,difficulty]);
 const showFeedback=(kind:'hit'|'miss')=>{setFeedback(kind);if(feedbackTimer.current)window.clearTimeout(feedbackTimer.current);feedbackTimer.current=window.setTimeout(()=>setFeedback(''),120)};
 const click=(e:React.MouseEvent)=>{if(phase!=='live'||!active.current)return;const r=stage.current?.getBoundingClientRect();if(!r)return;const x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;const tx=target.x,ty=target.y,dx=(x-tx)*r.width/100,dy=(y-ty)*r.height/100,d=Math.hypot(dx,dy),size=DIFF[difficulty].size;shotsRef.current+=1;setShots(shotsRef.current);if(d<=size/2+8){const ms=performance.now()-born.current;react.current.push(ms);dist.current.push(d);last.current=target;hitsRef.current+=1;setHits(hitsRef.current);setCombo(v=>v+1);showFeedback('hit');sound(true);active.current=false;setTimeout(()=>{if(phase==='live')next()},45)}else{over.current++;setCombo(0);showFeedback('miss');sound(false)}};
 if(phase==='intro')return <main className="game-page"><header className="game-header"><button className="back-btn" onClick={onBack}>← EXIT</button><div><p className="eyebrow">MICRO FLICK // PRECISION CONTROL</p><h1>마이크로 플릭</h1></div><div className="game-help">30 SEC</div></header><section className="setup panel"><p className="eyebrow">SMALL MOVE · CLEAN STOP · CLICK</p><h2>크게 휘두르지 말고 딱 붙여.</h2><p className="setup-copy">가까운 거리의 작은 타겟을 빠르게 잡고, 오버슈트 없이 미세 조정하는 훈련이야. 손목으로 크게 긁지 말고 필요한 만큼만 움직여.</p><div className="choice-grid difficulty-grid">{Object.entries(DIFF).map(([id,d])=><button key={id} className={`choice-card difficulty-${id} ${difficulty===id?'selected':''}`} onClick={()=>setDifficulty(id as Difficulty)}><span className="choice-kicker">{id.toUpperCase()}</span><strong>{d.label}</strong><em>타겟 {d.size}px · 이동거리 {d.gap}px</em><small>타겟을 맞힐 때까지 유지</small></button>)}</div><button className="primary-btn wide" onClick={()=>setPhase('live')}>▶ MICRO FLICK 시작 · 30초</button></section></main>;
 return <main className="game-page training-live"><header className="live-hud"><button className="back-btn" onClick={()=>{active.current=false;cancelAnimationFrame(raf.current);onBack()}}>× 종료</button><div><b>MICRO FLICK</b><span>{DIFF[difficulty].label}</span></div><div className="live-stats"><span>HIT <b>{hits}</b></span><span>SHOT <b>{shots}</b></span><span>COMBO <b>{combo}</b></span><span>TIME <b>{time}s</b></span><i className={`live-feedback ${feedback}`} aria-label={feedback?feedback:'feedback'} /></div></header><div ref={stage} className={`micro-stage feedback-${feedback}`} onClick={click}><div className="micro-target" style={{left:`${target.x}%`,top:`${target.y}%`,width:DIFF[difficulty].size,height:DIFF[difficulty].size}}/><CrosshairView config={crosshair} className="live-crosshair"/></div></main>
}
